# Generated by Django 4.1.7 on 2023-03-26 19:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('bill_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('bill_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_type', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('short_title', models.TextField(blank=True, null=True)),
                ('sponsor_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsor_state', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsor_party', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsor_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('gpo_pdf_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('congressdotgov_url', models.CharField(blank=True, max_length=255, null=True)),
                ('govtrack_url', models.CharField(blank=True, max_length=255, null=True)),
                ('introduced_date', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField()),
                ('last_vote', models.CharField(blank=True, max_length=255, null=True)),
                ('house_passage', models.CharField(blank=True, max_length=255, null=True)),
                ('senate_passage', models.CharField(blank=True, max_length=255, null=True)),
                ('enacted', models.CharField(blank=True, max_length=255, null=True)),
                ('vetoed', models.CharField(blank=True, max_length=255, null=True)),
                ('cosponsors', models.CharField(blank=True, max_length=255, null=True)),
                ('cosponsors_by_party', models.JSONField(blank=True, null=True)),
                ('committees', models.CharField(blank=True, max_length=255, null=True)),
                ('committee_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('subcommittee_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None)),
                ('primary_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('summary_short', models.TextField(blank=True, null=True)),
                ('latest_major_action_date', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_major_action', models.TextField(blank=True, null=True)),
                ('filtered_date', models.CharField(blank=True, max_length=255, null=True)),
                ('filtered_type', models.CharField(blank=True, max_length=255, null=True)),
                ('congress_version', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'bill',
                'verbose_name_plural': 'bills',
                'db_table': 'bills',
            },
        ),
    ]
