# Generated by Django 4.1.7 on 2023-03-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='congress_version',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
