version: "3"

services:
  backend:
    container_name: backend
    image: easy_politics_backend:latest
    build:
      context: .
      dockerfile: ./deploy/dev/Dockerfile
    env_file:
      - ./.envs/.dev
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:14
    env_file:
      - ./.envs/.dev
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
